version: '3.9'
services:
  backend:
    image: "${DOCKER_IMAGE_BACKEND?Variable not set}"
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    ports:
      - '8000:8000'
    volumes:
      - '.:/backend'

  frontend:
    image: "${DOCKER_IMAGE_FRONTEND?Variable not set}"
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args: 
        SSH_PRIVATE_KEY: "${SSH_PRIVATE_KEY}"
    restart: always
    ports: 
      - '3000:3000'
    volumes: 
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
