version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ./data-db:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081

  backend:
    image: ${DOCKER_IMAGE_BACKEND?Variable not set}
    container_name: ${DOCKER_CONTAINER_BACKEND?Variable not set}
    restart: unless-stopped
    depends_on:
      - mongodb
