FROM node:12-alpine3.10 as node-image

RUN apk update
RUN apk add --upgrade --no-cache g++ python3 openjdk11

# DEBUG
RUN apk add vim

WORKDIR /backend
COPY . .
RUN npm install

CMD ["npm", "run", "dev"]
