FROM node:12-alpine3.10 as node-image

WORKDIR /backend
COPY . .
RUN npm install
RUN npm run build

FROM node:12-alpine3.10
WORKDIR /backend
COPY package.json .
RUN npm install --only=production
COPY --from=node-image /backend/dist ./dist
# RUN npm install pm2 -g

# EXPOSE 8000

WORKDIR /backend/dist
CMD ["node", "index.js"]
